id: P005500
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01521
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༢༣
  author: ''
  volumes:
    1c722dc537e7496ab2b97c439aac4d8c:
      image_group_id: I5822
      title: ''
      volume_number: 1
      total_pages: 293
      base_file: v001.txt
